name: Test Workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Greeting
      run: echo "Hi There!"
    - name: Get the code itself
      uses: actions/checkout@v3
    # this is not really needed as ubuntu-latest comes with node16 pre-installed
    - name: Install NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 18
    # npm ci is safer here, possibly for tests and stuff as well
    - name: Install Dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    